########################
###### Data Path #######
########################

data: "/scratch1/mustafa/master/Data_Cleaned/all_run/assembly_cleaned_reads/all_contigs/"

########################
### Global Parameter ###
########################

global:
 check_results: False
 files: "fasta"
 threads: "32"
 memory: "200"
 CG: "roary"
 ### if all steps are defined as False, only a Core Genome Phylogeny is constructed ###
 qc: True
 annotation: False
 amr: False
 virulence: False
 mlst: False
 kraken: False

########################
#### Tool Parameter ####
########################

fastp:
  threads: "32"
  memory: "200"
  length_required: "100"
  qualified_quality_phred: "30"

annotation:
 db: "../Pipeline/databases/bakta/"
 genus: "Streptococcus"
 species: "Zooepidemicus"

cgmlst:
 threshold: "0.95"

amr:
 minid: "80"
 mincov: "80"
 database: "megares"

virulence:
  minid: "80"
  mincov: "80"
  database: "vfdb"

 roary:
  minid: "95"

tree:
  model: "GTR+G"
